<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Pengajuan</name>
   <tag></tag>
   <elementGuidId>19206a5c-9445-4138-aa7d-cf3200975d3f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='TreeView1t0']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#TreeView1t0</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>0f942691-84bd-4dff-9775-87685c29108f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>TreeView1_0 TreeView1_1 TreeView1_7</value>
      <webElementGuid>8bcfd53a-8a39-4931-8898-e9d51b2e86d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>Apps/ApprovalBanding/Pengajuan.aspx</value>
      <webElementGuid>127bc6f3-0280-4394-9d59-7fdee35c028b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>TreeView1t0</value>
      <webElementGuid>0f6152eb-1dfa-4f6f-8c57-fc78fe522bf0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Pengajuan</value>
      <webElementGuid>016ff2c7-e616-4406-bd55-ec2e08fd4f5a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;TreeView1t0&quot;)</value>
      <webElementGuid>35abdc49-62e8-40de-b796-f321935de5d1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='TreeView1t0']</value>
      <webElementGuid>eaffdbc8-7d22-48b0-b1ba-38508a821bb7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='TreeView1']/table/tbody/tr/td[2]/a</value>
      <webElementGuid>1516e72e-0b82-4a7d-a268-4b56852b8753</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Pengajuan')]</value>
      <webElementGuid>40cb5adf-7100-4940-9a2c-158241160412</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Skip Navigation Links.'])[1]/following::a[1]</value>
      <webElementGuid>37e817bc-8e13-4a87-b519-76f0d4bdcdd2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Approval List'])[1]/preceding::a[2]</value>
      <webElementGuid>488d3346-2c67-47b6-8bb3-86c9da8e6f81</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Whatsapp Information'])[1]/preceding::a[2]</value>
      <webElementGuid>60a89300-de93-4c7d-ac7a-5296651bfd91</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Pengajuan']/parent::*</value>
      <webElementGuid>c653f94a-2a79-44ff-b5b4-eb8d06b2bbe3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'Apps/ApprovalBanding/Pengajuan.aspx')]</value>
      <webElementGuid>be8757d1-5012-4bd2-ac76-df7d7fe27846</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/a</value>
      <webElementGuid>72f10c30-1996-46b2-adee-9fd9900ed34b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'Apps/ApprovalBanding/Pengajuan.aspx' and @id = 'TreeView1t0' and (text() = 'Pengajuan' or . = 'Pengajuan')]</value>
      <webElementGuid>74fda4ee-1a1c-45c5-bd15-69dfebf46618</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
