<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Angsuran_sebelum</name>
   <tag></tag>
   <elementGuidId>d203d005-6683-416a-b0c6-9ddc2afc3463</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;main_txtangsuran1&quot;)[count(. | //input[@id = 'main_txtangsuran1']) = count(//input[@id = 'main_txtangsuran1'])]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='main_txtangsuran1']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#main_txtangsuran1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a83f478c-7c29-47b4-87ce-dd3b0091ab90</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$main$txtangsuran1</value>
      <webElementGuid>37cc587e-1232-448d-963c-8a04b506fe86</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>9bd70315-bc10-406e-b86f-1fb982311de5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>2935500.00</value>
      <webElementGuid>2af90a21-719d-4b07-b992-3c8111c88c5b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>main_txtangsuran1</value>
      <webElementGuid>e45e09af-8b5d-418b-87ea-1fbd12c91738</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>disabled</name>
      <type>Main</type>
      <value>disabled</value>
      <webElementGuid>356db384-5754-447d-841f-b2edd5bc3d7f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>aspNetDisabled form-control</value>
      <webElementGuid>923cd0ad-9309-4115-8bb5-79c1052efacf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main_txtangsuran1&quot;)</value>
      <webElementGuid>6312542d-2ce2-46da-b113-2c39988e5b32</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='main_txtangsuran1']</value>
      <webElementGuid>047e0b6d-8292-404b-962e-2894b6666850</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='main_table']/tbody/tr[15]/td[2]/div/input</value>
      <webElementGuid>8e1f59f7-a3c0-449a-98d5-ad55986baf50</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[15]/td[2]/div/input</value>
      <webElementGuid>ca4d0ddc-f99f-4ce5-a7d3-4002e4fe1855</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'ctl00$main$txtangsuran1' and @type = 'text' and @id = 'main_txtangsuran1']</value>
      <webElementGuid>5515f0f9-b1cf-4283-b034-29856a9da801</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
