<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Penghasilan Cadeb_sebelum</name>
   <tag></tag>
   <elementGuidId>452fca0f-6b96-43b6-8287-63206e612692</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;main_txtpenghasilan1&quot;)[count(. | //input[@id = 'main_txtpenghasilan1']) = count(//input[@id = 'main_txtpenghasilan1'])]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='main_txtpenghasilan1']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#main_txtpenghasilan1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>faa86842-949f-4f56-b9be-9eb5bdf1452a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$main$txtpenghasilan1</value>
      <webElementGuid>73866f7e-803a-4e66-8ee0-21ba2d18cde9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>ddc35f21-deef-47d9-9456-911e310b0e58</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>main_txtpenghasilan1</value>
      <webElementGuid>813b81c1-739c-465c-9be1-68fbe363404f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>disabled</name>
      <type>Main</type>
      <value>disabled</value>
      <webElementGuid>90bc4ce2-195a-4a05-857f-6b7328800625</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>aspNetDisabled form-control</value>
      <webElementGuid>7964902b-d2c1-4252-a097-dfcb703e1727</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main_txtpenghasilan1&quot;)</value>
      <webElementGuid>7e33a57f-28ec-43e2-9a74-bca743d59fe6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='main_txtpenghasilan1']</value>
      <webElementGuid>68db236e-8015-48b7-993c-8b93f0727b7e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='main_table']/tbody/tr[16]/td[2]/div/input</value>
      <webElementGuid>3a984fb7-c2eb-4329-85c5-a22f61c06447</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[16]/td[2]/div/input</value>
      <webElementGuid>27cb43ea-82e1-4328-b426-013dd9e421a9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'ctl00$main$txtpenghasilan1' and @type = 'text' and @id = 'main_txtpenghasilan1']</value>
      <webElementGuid>5d9d0189-793a-4d63-86e4-d81faef64e00</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
