<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Produk_sesudah</name>
   <tag></tag>
   <elementGuidId>7ad494bd-87e6-4163-94a5-bb95ec97134a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='main_txtproduk2']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#main_txtproduk2</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;main_txtproduk2&quot;)[count(. | //input[@id = 'main_txtproduk2']) = count(//input[@id = 'main_txtproduk2'])]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e1df069f-d340-465a-be23-0ed333ded522</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$main$txtproduk2</value>
      <webElementGuid>1a5f5b7c-d766-4c8e-b764-ffc193b4e467</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>3e5c3f99-dc31-4499-8c37-7839eae120ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>main_txtproduk2</value>
      <webElementGuid>11bf2dc9-868f-4fb8-809d-1b4cd3465c16</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>3841f7b5-ca1a-47bb-a2bc-4fd6fee52e6a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main_txtproduk2&quot;)</value>
      <webElementGuid>46dcc0ef-ccd0-433d-b912-2a46d02f018a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='main_txtproduk2']</value>
      <webElementGuid>156141a4-4dfc-4d32-8b86-c385067f33d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='main_table']/tbody/tr[2]/td[3]/div/input</value>
      <webElementGuid>915c1f49-6f97-4e08-984a-2fb102a3d7c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[3]/div/input</value>
      <webElementGuid>ba88a98c-fe23-40dd-b4bf-c6891f1ba42e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'ctl00$main$txtproduk2' and @type = 'text' and @id = 'main_txtproduk2']</value>
      <webElementGuid>0f0a534c-3743-436e-9eb7-6c9298733131</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
