<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_MRP_sebelum</name>
   <tag></tag>
   <elementGuidId>bd0c0574-6720-4c62-96b6-55921372b220</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;main_txtmrp1&quot;)[count(. | //input[@id = 'main_txtmrp1']) = count(//input[@id = 'main_txtmrp1'])]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='main_txtmrp1']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#main_txtmrp1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>7076f584-d282-4926-aa92-109b00fda2cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$main$txtmrp1</value>
      <webElementGuid>e30a128d-577f-4c90-aced-c3c241f80764</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>4ceec8aa-e3bb-4843-889b-b69bb03676e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>main_txtmrp1</value>
      <webElementGuid>674661ec-5152-4c06-9122-e7ae350dae47</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>disabled</name>
      <type>Main</type>
      <value>disabled</value>
      <webElementGuid>734e9f93-859b-4e0d-88f4-083a9af119da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>aspNetDisabled form-control</value>
      <webElementGuid>6d6e98fa-9d2e-48d9-b2ba-13c6fe2f7d0a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main_txtmrp1&quot;)</value>
      <webElementGuid>10851fd3-beea-45fa-b568-f4af4556419a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='main_txtmrp1']</value>
      <webElementGuid>b0e916d1-2544-470d-b10b-ba6574f9e662</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='main_table']/tbody/tr[7]/td[2]/div/input</value>
      <webElementGuid>88c206c4-66cd-4556-868b-dc0227b2befd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[7]/td[2]/div/input</value>
      <webElementGuid>a36a1225-8b3e-422d-9e2b-7c5939c0a0cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'ctl00$main$txtmrp1' and @type = 'text' and @id = 'main_txtmrp1']</value>
      <webElementGuid>a6935443-352a-4b75-bd03-270ec4f75057</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
