<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Down Payment_sebelum</name>
   <tag></tag>
   <elementGuidId>d840c0cd-e3fe-4288-876b-ba2c9af35ae4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;main_txtdownpayment1&quot;)[count(. | //input[@id = 'main_txtdownpayment1']) = count(//input[@id = 'main_txtdownpayment1'])]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='main_txtdownpayment1']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#main_txtdownpayment1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>883a0158-9d15-45a0-a178-9c36ecac7ec5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$main$txtdownpayment1</value>
      <webElementGuid>aa507964-8837-4bb3-87e6-581403a6c11f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>7e3b3ffe-a515-466a-a5ed-9ff95d3d24f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>29.40</value>
      <webElementGuid>d2d93ce3-db8e-4633-ac78-2537ae3f8f85</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>main_txtdownpayment1</value>
      <webElementGuid>e0489cfe-975b-460e-8349-371836a13f7a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>disabled</name>
      <type>Main</type>
      <value>disabled</value>
      <webElementGuid>d83202c2-52db-4dc3-9cef-1209f136ad1c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>aspNetDisabled form-control</value>
      <webElementGuid>2482129b-9afd-4f96-bbbc-58ee2576435f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main_txtdownpayment1&quot;)</value>
      <webElementGuid>96113ffc-c0e5-4701-b842-5767ae7b77d1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='main_txtdownpayment1']</value>
      <webElementGuid>1833dca9-3428-4bc7-bd3c-49bf874e3428</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='main_table']/tbody/tr[9]/td[2]/div/input</value>
      <webElementGuid>a5a6cc47-79ac-4264-84f8-eaedd87c8a2c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[9]/td[2]/div/input</value>
      <webElementGuid>a27e7b77-09ef-497d-b8a5-2f0b10df08f6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'ctl00$main$txtdownpayment1' and @type = 'text' and @id = 'main_txtdownpayment1']</value>
      <webElementGuid>51c72d80-0457-4aff-a672-d60ff3801dec</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
