<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Produk_sebelum</name>
   <tag></tag>
   <elementGuidId>701aa58f-c0cf-4941-9e83-ead017735ab2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='main_txtproduk1']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#main_txtproduk1</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;main_txtproduk1&quot;)[count(. | //input[@id = 'main_txtproduk1']) = count(//input[@id = 'main_txtproduk1'])]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>5ea380fa-74df-4b4f-811b-b84067d244ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$main$txtproduk1</value>
      <webElementGuid>df260168-0f36-4d43-95b2-eaf541c6be7e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>cdc1d47d-cb99-41ae-ba04-fa3ff2a06dd2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>4W Used Car</value>
      <webElementGuid>569ebb1b-0e30-454c-ba9f-138b82acb3ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>main_txtproduk1</value>
      <webElementGuid>99e346e7-26da-40d1-adc9-2c67bbb8388e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>disabled</name>
      <type>Main</type>
      <value>disabled</value>
      <webElementGuid>8bbd6d16-ae18-4f84-88ff-8b155ae8f7e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>aspNetDisabled form-control</value>
      <webElementGuid>a229098a-2201-49e5-8f75-1fc25042d6e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main_txtproduk1&quot;)</value>
      <webElementGuid>ab111079-d90e-4581-8e55-c0e6e802dd26</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='main_txtproduk1']</value>
      <webElementGuid>e2b9fcc9-9a21-4e10-9d60-0ebbf4817d1c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='main_table']/tbody/tr[2]/td[2]/div/input</value>
      <webElementGuid>3a8f992c-1bb1-4b5d-96ed-2858f55a70c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/div/input</value>
      <webElementGuid>89f025fb-c0af-4932-bfec-930f87131c62</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'ctl00$main$txtproduk1' and @type = 'text' and @id = 'main_txtproduk1']</value>
      <webElementGuid>e3202a27-66b2-428f-a33e-9fc2e052bcb1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
