<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_NTF Kapitalisasi_sebelum</name>
   <tag></tag>
   <elementGuidId>e2c3d848-6bd2-4449-b61c-9fbc1fc8d485</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;main_txtntfkapitalisasi1&quot;)[count(. | //input[@id = 'main_txtntfkapitalisasi1']) = count(//input[@id = 'main_txtntfkapitalisasi1'])]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='main_txtntfkapitalisasi1']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#main_txtntfkapitalisasi1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>49b5f6a3-413d-4d02-880b-a90ce0ed7de2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$main$txtntfkapitalisasi1</value>
      <webElementGuid>579c7fc6-8b91-4a95-b979-6809791594ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>ead06b28-07e2-4959-8d55-631593547317</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>main_txtntfkapitalisasi1</value>
      <webElementGuid>a66dfc7f-9a8f-418f-a1eb-340eee7f827f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>disabled</name>
      <type>Main</type>
      <value>disabled</value>
      <webElementGuid>f448592b-baa4-480a-b40d-00b829bbd0bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>aspNetDisabled form-control</value>
      <webElementGuid>1fb1caa4-64f8-4726-96b2-e2031f544e93</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main_txtntfkapitalisasi1&quot;)</value>
      <webElementGuid>f0b0a55b-d3c6-4343-910f-857fe780f5e5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='main_txtntfkapitalisasi1']</value>
      <webElementGuid>8771b39b-9db1-40a7-a84a-fabc770b8f11</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='main_table']/tbody/tr[13]/td[2]/div/input</value>
      <webElementGuid>abb16ff7-ca37-4ea6-a618-25cf975e28d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[13]/td[2]/div/input</value>
      <webElementGuid>f99148bc-759b-4d08-ab0b-e9983c3b2ff9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'ctl00$main$txtntfkapitalisasi1' and @type = 'text' and @id = 'main_txtntfkapitalisasi1']</value>
      <webElementGuid>12c55981-ce99-4e42-96d2-802dccdaa2e7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
