<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Supplier_sebelum</name>
   <tag></tag>
   <elementGuidId>8afaacd8-6162-4843-9e9b-1342b5799063</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;main_txtsupplier1&quot;)[count(. | //input[@id = 'main_txtsupplier1']) = count(//input[@id = 'main_txtsupplier1'])]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='main_txtsupplier1']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#main_txtsupplier1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>bbd11778-3e63-4629-aabd-0033824ac980</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$main$txtsupplier1</value>
      <webElementGuid>c41f368a-da84-40b3-a65b-e57ea6751726</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>660553ed-28be-448a-9cce-a309a19127ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>SINAR MOTOR - BANDUNG</value>
      <webElementGuid>55bc0a8d-e002-40fb-9e4a-9b1c7ae76987</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>main_txtsupplier1</value>
      <webElementGuid>35316510-60fe-487f-9179-df8cb4f39f7b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>disabled</name>
      <type>Main</type>
      <value>disabled</value>
      <webElementGuid>5fc356b1-2d4e-4e4f-9cf3-b1b37c2f4975</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>aspNetDisabled form-control</value>
      <webElementGuid>17f5e768-a966-4b4b-b91c-fe17fdf8cb5b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main_txtsupplier1&quot;)</value>
      <webElementGuid>1904a05a-032f-4780-ae90-02231059dec2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='main_txtsupplier1']</value>
      <webElementGuid>e6023431-f123-4d43-8363-fa71594e3380</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='main_table']/tbody/tr[3]/td[2]/div/input</value>
      <webElementGuid>a64ed3a1-3066-4cbb-978e-3db36e2cfd9b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[3]/td[2]/div/input</value>
      <webElementGuid>5d056223-3db4-4c4a-8f96-f266da3464bd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'ctl00$main$txtsupplier1' and @type = 'text' and @id = 'main_txtsupplier1']</value>
      <webElementGuid>23a6d02e-d622-4577-88c3-e259c1b4aaf4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
