<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_DSR_sesudah</name>
   <tag></tag>
   <elementGuidId>f56340bf-116a-4b97-a6ef-c6038521dce4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='main_txtdsr2']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#main_txtdsr2</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>078e3a39-95e8-4abd-b149-2bde0132b752</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$main$txtdsr2</value>
      <webElementGuid>284fa4e8-3b2a-46ca-8e0c-07611a5f618e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>6d08bf8b-879b-429d-9d10-e0e4ccb48568</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>main_txtdsr2</value>
      <webElementGuid>d73558d6-f15c-4f75-8432-b092ebf5aadf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>42e0a05f-f9f4-4012-8b8e-c4ab01e1640e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeyup</name>
      <type>Main</type>
      <value>FormatCurrency(this)</value>
      <webElementGuid>a5204e50-7a63-456f-a224-f61b0be69f1f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeypress</name>
      <type>Main</type>
      <value>return isnumerickey(event);</value>
      <webElementGuid>fb7e9cef-d39e-4a43-837b-f1f6bfd76d75</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main_txtdsr2&quot;)</value>
      <webElementGuid>e6c8714a-e3a1-4dc9-8ad2-d5a7fc3bb6a9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='main_txtdsr2']</value>
      <webElementGuid>d40d77e8-cc15-4f8b-8696-416208da6470</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='main_table']/tbody/tr[17]/td[3]/div/input</value>
      <webElementGuid>13e3f494-b4d3-4f19-9301-b399117b42d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[17]/td[3]/div/input</value>
      <webElementGuid>b8f188f3-078c-43cc-b34b-063947be4c5c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'ctl00$main$txtdsr2' and @type = 'text' and @id = 'main_txtdsr2']</value>
      <webElementGuid>195affee-976a-40b0-9fd7-7dad746822da</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
