<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_TDP_sesudah</name>
   <tag></tag>
   <elementGuidId>4f2235cb-bc4e-447d-b8c2-52ea19ef9d9d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='main_txttdp2']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#main_txttdp2</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>487e3955-6554-4a6b-9ae0-2e74ef89bc83</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$main$txttdp2</value>
      <webElementGuid>b0ddb1f5-7629-4e2a-ab7a-8e263c35f86e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>14e73b64-bad9-41a7-b043-878be027897f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>main_txttdp2</value>
      <webElementGuid>126872f1-420a-48b0-9424-e5ba7f8a5749</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>39cec449-f63f-4290-b400-95b6ec7c870f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeyup</name>
      <type>Main</type>
      <value>FormatCurrency(this)</value>
      <webElementGuid>48bf838d-987d-40f1-b5f6-af55bea9d699</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeypress</name>
      <type>Main</type>
      <value>return isnumerickey(event);</value>
      <webElementGuid>9fc8e255-c7e9-4427-952f-1c3a87bef6dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main_txttdp2&quot;)</value>
      <webElementGuid>92903b95-1dc9-4239-98dc-a3f494d1edfe</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='main_txttdp2']</value>
      <webElementGuid>99a26587-71fc-4c67-873a-7312c6abda5a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='main_table']/tbody/tr[11]/td[3]/div/input</value>
      <webElementGuid>71911bba-7b16-4731-ad2a-ee361ae9d489</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[11]/td[3]/div/input</value>
      <webElementGuid>4659b67a-9988-414f-8bb5-d85fc4c772dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'ctl00$main$txttdp2' and @type = 'text' and @id = 'main_txttdp2']</value>
      <webElementGuid>c10170d3-3b17-4ed0-afdf-21a47e6c4588</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
