<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Supplier_sesudah</name>
   <tag></tag>
   <elementGuidId>37da7821-b24b-4d7b-aff6-cf78cb37d73d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='main_txtsupplier2']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#main_txtsupplier2</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f7a98b2c-a9e7-41eb-8d43-33a53f38a12f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$main$txtsupplier2</value>
      <webElementGuid>7c7bdbfc-b75e-4011-b6f2-bd06232219b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>7d77df5b-03aa-4052-98c2-17be12502af8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>main_txtsupplier2</value>
      <webElementGuid>91a62b9e-f6fc-4d26-a58b-4ace444a5223</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>6e63461f-251d-4296-b4fa-d87e99cf92ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main_txtsupplier2&quot;)</value>
      <webElementGuid>4af6c45f-e42f-4bee-9751-23d80eda0c95</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='main_txtsupplier2']</value>
      <webElementGuid>b8ab5717-da07-455f-9a1f-586717f0e65d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='main_table']/tbody/tr[3]/td[3]/div/input</value>
      <webElementGuid>2e09557f-d915-40ee-8ae9-937bb9f3687e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[3]/td[3]/div/input</value>
      <webElementGuid>36f493ac-7d98-4a79-ac7d-b88655fccce8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'ctl00$main$txtsupplier2' and @type = 'text' and @id = 'main_txtsupplier2']</value>
      <webElementGuid>de58a2fd-99b9-4dee-ba31-0b2b3e93a13b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
