<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_NTF Kapitalisasi_sesudah</name>
   <tag></tag>
   <elementGuidId>dfba4699-506a-42e9-906f-e79376aa3ce2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='main_txtntfkapitalisasi2']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#main_txtntfkapitalisasi2</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e087a096-4055-43c8-b5de-35dca9356b11</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$main$txtntfkapitalisasi2</value>
      <webElementGuid>c38f3195-d35d-4751-bc19-5b91e85e8177</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>51ef3706-91be-49a8-b684-6215b7d0457c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>main_txtntfkapitalisasi2</value>
      <webElementGuid>9b64dc2e-a6e9-4fec-881b-605135c99289</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>3dc3face-17d1-4faf-b33b-7ed3dba55c0c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeyup</name>
      <type>Main</type>
      <value>FormatCurrency(this)</value>
      <webElementGuid>953626c3-cd72-4dd2-8d42-c893240cebe6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeypress</name>
      <type>Main</type>
      <value>return isnumerickey(event);</value>
      <webElementGuid>f49da2dc-6111-4cbb-908b-d5f65cd24bc5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main_txtntfkapitalisasi2&quot;)</value>
      <webElementGuid>b8fd409e-a101-460f-9d5c-b384d9135ff5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='main_txtntfkapitalisasi2']</value>
      <webElementGuid>198d1625-bee0-4c70-a3dc-1d49de71c9f0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='main_table']/tbody/tr[13]/td[3]/div/input</value>
      <webElementGuid>08cc5436-6648-4c88-a52a-56a86f6f58de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[13]/td[3]/div/input</value>
      <webElementGuid>00142b54-5b99-40f0-b8c4-c56c1eeaa1ed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'ctl00$main$txtntfkapitalisasi2' and @type = 'text' and @id = 'main_txtntfkapitalisasi2']</value>
      <webElementGuid>f158afef-9aa5-4612-bdc8-c5e6d0b4efee</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
