<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Tenor_sebelum</name>
   <tag></tag>
   <elementGuidId>27c4a7a2-b4ec-4646-9a78-c8ff502ce633</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;main_txttenor1&quot;)[count(. | //input[@id = 'main_txttenor1']) = count(//input[@id = 'main_txttenor1'])]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='main_txttenor1']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#main_txttenor1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e1fa5591-a446-493c-97b0-487a3c7c28c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$main$txttenor1</value>
      <webElementGuid>f96f4494-0fdd-4aa1-b063-79a90ddc77b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>4006c743-c441-4bdb-a68c-508dc910ab6d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>60</value>
      <webElementGuid>369319c9-1399-4bd4-9884-16394ed851e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>main_txttenor1</value>
      <webElementGuid>07a3f367-da6d-45e4-b038-a3191e77346b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>disabled</name>
      <type>Main</type>
      <value>disabled</value>
      <webElementGuid>36b0266a-8b4e-41ff-a67e-e2b089fb7b3c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>aspNetDisabled form-control</value>
      <webElementGuid>b5f01ed9-8bc4-494e-a0b5-48eaeede2fda</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main_txttenor1&quot;)</value>
      <webElementGuid>8b81107e-e5f0-4b96-99b6-3ce77dc5d5a9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='main_txttenor1']</value>
      <webElementGuid>2d6e4c16-c55c-4de1-b271-8fc4c6c0624f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='main_table']/tbody/tr[14]/td[2]/div/input</value>
      <webElementGuid>3ec5b211-3f31-485a-accd-09a707a4699f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[14]/td[2]/div/input</value>
      <webElementGuid>90164f78-b82b-4079-bcbb-2372039c7a32</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'ctl00$main$txttenor1' and @type = 'text' and @id = 'main_txttenor1']</value>
      <webElementGuid>0b50a9f2-2219-4b53-a2d1-e6925ef17eea</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
