<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_DSR_sebelum</name>
   <tag></tag>
   <elementGuidId>6e2232b8-0909-491f-b109-186a8778d072</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;main_txtdsr1&quot;)[count(. | //input[@id = 'main_txtdsr1']) = count(//input[@id = 'main_txtdsr1'])]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='main_txtdsr1']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#main_txtdsr1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c1a6b393-a513-42d6-a529-4e28bfe22823</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$main$txtdsr1</value>
      <webElementGuid>9fa0a1ec-9438-4498-ab90-b9d0c99300cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>4b79bb97-f89a-4049-8abd-32ca66db48ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>main_txtdsr1</value>
      <webElementGuid>af8d6f77-b0d9-4059-afb9-92b20919fdb2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>disabled</name>
      <type>Main</type>
      <value>disabled</value>
      <webElementGuid>13e5cf33-3e93-4de8-a381-8465818c0758</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>aspNetDisabled form-control</value>
      <webElementGuid>d542fd77-2b6b-44ae-a605-be6b7b917797</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main_txtdsr1&quot;)</value>
      <webElementGuid>b32e9f11-1042-45c2-afdd-92b63e9db752</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='main_txtdsr1']</value>
      <webElementGuid>0b461d72-5b1e-43ed-bd3a-5eb3ed81bf1c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='main_table']/tbody/tr[17]/td[2]/div/input</value>
      <webElementGuid>f36e42f6-2720-4b66-b9ea-f8ba06a6cdd1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[17]/td[2]/div/input</value>
      <webElementGuid>14ac0727-5801-4875-9c61-66a54bbd3bdd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'ctl00$main$txtdsr1' and @type = 'text' and @id = 'main_txtdsr1']</value>
      <webElementGuid>192233fd-ee4b-4bf1-8e20-2dd8f4246afe</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
