<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Unit Pengajuan_sebelum</name>
   <tag></tag>
   <elementGuidId>25828824-522d-4dea-85c8-c856eda18058</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;main_txtunit1&quot;)[count(. | //input[@id = 'main_txtunit1']) = count(//input[@id = 'main_txtunit1'])]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='main_txtunit1']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#main_txtunit1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>0e144982-d226-46e6-9065-2900cdfbe756</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$main$txtunit1</value>
      <webElementGuid>99a7d52c-919d-40fa-a760-fba4218ed020</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>3ea29317-0546-4f74-b13d-9361028cd084</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>TOYOTA CALYA 1.2 G MT</value>
      <webElementGuid>31e19b41-29fb-4759-9d49-c4b13d64ee13</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>main_txtunit1</value>
      <webElementGuid>980a46c1-9337-414c-8db8-b3c6c3f0bcbc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>disabled</name>
      <type>Main</type>
      <value>disabled</value>
      <webElementGuid>27bd5b2b-ca87-4e57-8050-36c8ef63ece4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>aspNetDisabled form-control</value>
      <webElementGuid>ce3a5ee7-be30-4c7c-abbb-e1bcc8d3bd45</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main_txtunit1&quot;)</value>
      <webElementGuid>88e8143d-6755-42e4-8a21-9e4af1f8fddb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='main_txtunit1']</value>
      <webElementGuid>8901ad8c-5ce5-4d62-9cba-1b1404db6f01</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='main_table']/tbody/tr[4]/td[2]/div/input</value>
      <webElementGuid>1e4ade47-2db8-4998-8cea-a7d671cb6adb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[4]/td[2]/div/input</value>
      <webElementGuid>44c85916-6115-4d7b-af84-394c58bb35d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'ctl00$main$txtunit1' and @type = 'text' and @id = 'main_txtunit1']</value>
      <webElementGuid>28523a0c-6a61-422a-8db6-c0d9a9245295</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
