<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_TDP_sebelum</name>
   <tag></tag>
   <elementGuidId>847fbae6-4bd6-4c58-b9ce-226a3032438e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;main_txttdp1&quot;)[count(. | //input[@id = 'main_txttdp1']) = count(//input[@id = 'main_txttdp1'])]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='main_txttdp1']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#main_txttdp1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>feb4d855-b1a0-495e-a3b4-4c13c652c140</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$main$txttdp1</value>
      <webElementGuid>60a3e9fe-eaed-41c7-9f72-4485b0bf4bb0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>a3a4165a-a51d-491d-a3f1-be6639db11d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>41748000.00</value>
      <webElementGuid>79a791cd-d955-4b63-90f0-822231af00c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>main_txttdp1</value>
      <webElementGuid>c1841700-5b7e-4235-a9db-a533f51d2f05</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>disabled</name>
      <type>Main</type>
      <value>disabled</value>
      <webElementGuid>18fe1de7-c4ef-4a67-b494-589fd1cb01de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>aspNetDisabled form-control</value>
      <webElementGuid>4f05a5a4-1374-45aa-b663-25068c9ec228</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main_txttdp1&quot;)</value>
      <webElementGuid>a0e90da8-10b0-404d-a499-06ee2811d8ae</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='main_txttdp1']</value>
      <webElementGuid>903c8ea8-144e-48c0-b4a4-fe3a3d5e6253</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='main_table']/tbody/tr[11]/td[2]/div/input</value>
      <webElementGuid>3e694def-4543-417c-955e-d47ccb6be77a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[11]/td[2]/div/input</value>
      <webElementGuid>347f3422-c64b-4d9c-8c8d-2c57f3cce4bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'ctl00$main$txttdp1' and @type = 'text' and @id = 'main_txttdp1']</value>
      <webElementGuid>3839ed2c-1b75-4e1f-8f16-da8b9ae3864f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
