<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Opportunity_sesudah</name>
   <tag></tag>
   <elementGuidId>9667b866-8a96-4856-b102-9ccd74e909b5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='main_txtopportunity2']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#main_txtopportunity2</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>0814d6b1-c095-4e0f-b243-1ea004a039f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$main$txtopportunity2</value>
      <webElementGuid>32ee4140-b4cf-45b5-b01f-71b43e138549</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>5</value>
      <webElementGuid>ee2a2802-61b8-44bc-b40a-3ab61510261d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>cols</name>
      <type>Main</type>
      <value>38</value>
      <webElementGuid>ec8643d2-4719-4cd4-b0b0-2bac679bd171</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>main_txtopportunity2</value>
      <webElementGuid>22c2fe12-15d4-4011-ac64-fff0da1a0951</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main_txtopportunity2&quot;)</value>
      <webElementGuid>a9d2eb74-43e9-466e-bbd4-7de917da50fe</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='main_txtopportunity2']</value>
      <webElementGuid>8aac50b9-8015-4175-9d73-f7ccc8f80176</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='main_table']/tbody/tr[21]/td[3]/div/textarea</value>
      <webElementGuid>64efa7ee-7b67-4ca0-a3ff-b70dd1ad6816</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[21]/td[3]/div/textarea</value>
      <webElementGuid>5caf1eeb-88fa-4dff-a999-3d5a1671a8f6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@name = 'ctl00$main$txtopportunity2' and @id = 'main_txtopportunity2']</value>
      <webElementGuid>f9010995-9039-4d2a-be6a-54a443c86377</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
