<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Rekomendasi Komite Risk_sebelum</name>
   <tag></tag>
   <elementGuidId>d650ec49-7389-4e1a-8f45-9fd487cbacb5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;main_txtrekomendasi1&quot;)[count(. | //textarea[@id = 'main_txtrekomendasi1']) = count(//textarea[@id = 'main_txtrekomendasi1'])]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='main_txtrekomendasi1']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#main_txtrekomendasi1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>d0969912-f186-4945-ac43-87bffad8516b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$main$txtrekomendasi1</value>
      <webElementGuid>b8ef9c56-d35f-4206-aaf7-5165a60c8d3d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>5</value>
      <webElementGuid>ac3cd111-10d0-4e33-9e9b-1583518c1b23</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>cols</name>
      <type>Main</type>
      <value>38</value>
      <webElementGuid>4baed1d8-4bcf-44c4-a299-d251e167e95d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>main_txtrekomendasi1</value>
      <webElementGuid>ed8c97a4-0131-4763-867e-562950371ba1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>disabled</name>
      <type>Main</type>
      <value>disabled</value>
      <webElementGuid>ac23d7bb-6ff1-4fe1-874d-ab0730cfef33</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>aspNetDisabled</value>
      <webElementGuid>1f9c0d41-9f0b-4521-801e-20502cec3797</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main_txtrekomendasi1&quot;)</value>
      <webElementGuid>9715b37e-8662-41d4-a245-70dd311fae0b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='main_txtrekomendasi1']</value>
      <webElementGuid>5725a454-c197-467d-93e6-bb5c70b4ed2b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='main_table']/tbody/tr[18]/td[2]/div/textarea</value>
      <webElementGuid>a956c0fd-77b8-4f96-ae05-3840b2398030</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>3e574dd0-779a-4b3d-8a62-cc17c111f5f2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@name = 'ctl00$main$txtrekomendasi1' and @id = 'main_txtrekomendasi1']</value>
      <webElementGuid>3f7221ee-9f6b-4f66-86f8-53e9f18940ee</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
