<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Rekomendasi Komite Risk_sesudah</name>
   <tag></tag>
   <elementGuidId>7afab23a-4b9d-43a4-8c7a-216dc604b142</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='main_txtrekomendasi2']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#main_txtrekomendasi2</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>29adaf91-bc2d-401d-84a9-e841ae81a643</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$main$txtrekomendasi2</value>
      <webElementGuid>cb3189b3-ea20-4fbb-8db3-48ca501f03cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>5</value>
      <webElementGuid>687858ec-fb0e-45ec-9eb8-06737fd25248</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>cols</name>
      <type>Main</type>
      <value>38</value>
      <webElementGuid>48f151e7-d100-4e75-a2bb-8282c0a34000</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>main_txtrekomendasi2</value>
      <webElementGuid>18460b1b-b1ae-4906-8ccc-7186b9652bd9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main_txtrekomendasi2&quot;)</value>
      <webElementGuid>0944c1a7-250a-49e3-b5fd-ea5200a4ef4b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='main_txtrekomendasi2']</value>
      <webElementGuid>37d1e518-0a16-4dc4-8b2c-87940c18e013</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='main_table']/tbody/tr[18]/td[3]/div/textarea</value>
      <webElementGuid>b2782f7a-5780-422c-aee8-489d4c7adc38</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[3]/div/textarea</value>
      <webElementGuid>076b765d-6e27-4dab-b5d0-dc99e68f5dac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@name = 'ctl00$main$txtrekomendasi2' and @id = 'main_txtrekomendasi2']</value>
      <webElementGuid>f00f08bf-586f-4b1e-9723-e8a3ae17f4ce</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
