<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>SPV_Jodi Yuliardi</name>
   <tag></tag>
   <elementGuidId>f4e28ac0-aee9-4f54-bd0e-513cb0183316</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>[value='JodiY']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>b68f2195-218c-4d02-986e-f63c7f4cc4c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>[value='JodiY']</value>
      <webElementGuid>3250a271-42e1-46dd-bc5a-f88203461bc1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//option[.='Jodi Yuliardi']</value>
      <webElementGuid>0f758efb-0245-4be9-9990-05c9f035612c</webElementGuid>
   </webElementProperties>
</WebElementEntity>
