<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>THREAT_sesudah</name>
   <tag></tag>
   <elementGuidId>131f7da7-7919-4494-96d7-2c043aa4f61f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='main_txtthread2']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#main_txtthread2</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>70a260b3-3487-4da5-876e-3aaf66ba3297</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$main$txtthread2</value>
      <webElementGuid>1934ecb4-0219-403d-bd90-f2aa3111c005</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>5</value>
      <webElementGuid>54e98dce-779d-4b9c-8e08-fb3ac88e9db9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>cols</name>
      <type>Main</type>
      <value>38</value>
      <webElementGuid>92ae34ec-0472-428c-9901-08b7eba6d776</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>main_txtthread2</value>
      <webElementGuid>73f13ae9-4f29-4d12-9a5d-b7e345cea89e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main_txtthread2&quot;)</value>
      <webElementGuid>f37d5505-ba0c-4d23-aa59-f1a0f661de94</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='main_txtthread2']</value>
      <webElementGuid>f5638b1f-4645-4b37-8833-45d08b8ab38e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='main_table']/tbody/tr[22]/td[3]/div/textarea</value>
      <webElementGuid>88a8c5c4-d189-4d5f-aea7-cfada9e2bb52</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[22]/td[3]/div/textarea</value>
      <webElementGuid>4a9f19dc-d665-4e57-8dd9-90dc707a3ac7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@name = 'ctl00$main$txtthread2' and @id = 'main_txtthread2']</value>
      <webElementGuid>d65d48de-c9cd-4637-88c8-5cff41b3cf76</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
