<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Weakness_sesudah</name>
   <tag></tag>
   <elementGuidId>4cd1ab82-09d5-4bb9-9237-e9d1961f8717</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='main_txtweaknes2']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#main_txtweaknes2</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>ca602c34-e36d-4841-a173-f1d08c0d3ec6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$main$txtweaknes2</value>
      <webElementGuid>68d27231-0878-40a7-b7ee-3bfec66f9710</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>5</value>
      <webElementGuid>f54222d9-33e1-4af9-a775-2902590f275c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>cols</name>
      <type>Main</type>
      <value>38</value>
      <webElementGuid>a9040e85-c52e-40f7-9bad-b1af85bc895a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>main_txtweaknes2</value>
      <webElementGuid>b5d381b9-7023-4632-a622-dd23167eaee0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main_txtweaknes2&quot;)</value>
      <webElementGuid>237384d3-774f-4294-b9e8-8a66789f4dae</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='main_txtweaknes2']</value>
      <webElementGuid>f31c54aa-715d-48ae-b83e-018be241c5eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='main_table']/tbody/tr[20]/td[3]/div/textarea</value>
      <webElementGuid>8bd03f05-ebc2-4d65-9262-c0a1d39263f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[20]/td[3]/div/textarea</value>
      <webElementGuid>eba4ea44-cb94-4758-928c-e7079ef17982</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@name = 'ctl00$main$txtweaknes2' and @id = 'main_txtweaknes2']</value>
      <webElementGuid>4691e6b0-0827-4bbf-b15a-bd98d41f90d1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
