<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Action_approval</name>
   <tag></tag>
   <elementGuidId>7c582f32-46f9-4921-96be-34aa3dd92120</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='main_grd_approval']/tbody/tr[2]/td[7]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>td:nth-of-type(7) > a.btn.btn-primary.btn-sm</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>4b7416be-4f34-44b6-a09d-5e7fc0131c32</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>../OPEX/FrmApprovalMemo.aspx?docno=571/10022023/0003&amp;Docid=eMEMO&amp;Branchid=PANAM</value>
      <webElementGuid>84b487a8-947a-46ea-99ac-31f36e1a4709</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary btn-sm</value>
      <webElementGuid>64b485bf-ead7-4eb8-bd67-ea0374f4fb6a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Approval Form</value>
      <webElementGuid>2cd3d364-d88e-460c-b726-837a8fc45b38</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main_grd_approval&quot;)/tbody[1]/tr[2]/td[7]/a[@class=&quot;btn btn-primary btn-sm&quot;]</value>
      <webElementGuid>14e9d502-5254-4241-b0e7-02c40fcb055e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='main_grd_approval']/tbody/tr[2]/td[7]/a</value>
      <webElementGuid>b2efd983-eaf1-475a-b5cf-cb7668d65dfe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='APR'])[1]/following::a[1]</value>
      <webElementGuid>fbc14616-c1a2-442b-a673-4ae0301b274a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='EkoP_ME'])[1]/following::a[1]</value>
      <webElementGuid>e4ee56d2-d2b3-487f-9d9b-1f5a49c5032a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='GORONTALO'])[2]/preceding::a[2]</value>
      <webElementGuid>ea17f043-9f96-4781-8d02-f14653d04484</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='eMEMO'])[2]/preceding::a[2]</value>
      <webElementGuid>4b62c2c5-e2f3-4a26-81be-ed8235303767</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '../OPEX/FrmApprovalMemo.aspx?docno=571/10022023/0003&amp;Docid=eMEMO&amp;Branchid=PANAM')]</value>
      <webElementGuid>2394a978-a79c-4d19-9ca0-5f7f92ec8f55</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[7]/a</value>
      <webElementGuid>46e3a8ae-6e86-4f10-b2c0-d6ea2b0b506c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '../OPEX/FrmApprovalMemo.aspx?docno=571/10022023/0003&amp;Docid=eMEMO&amp;Branchid=PANAM' and @title = 'Approval Form']</value>
      <webElementGuid>25976fdc-65c1-4edf-9828-9e9d4efd1e2b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
