<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Workflow</name>
   <tag></tag>
   <elementGuidId>b51f0536-3260-4c70-9108-86f8adde3db7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//option[.='Workflow']</value>
      </entry>
      <entry>
         <key>BASIC</key>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>ed7ae168-7d07-4f40-a003-fc6fc6e1a19f</webElementGuid>
   </webElementProperties>
</WebElementEntity>
